=== annush-hub/annush-hub.github.io/dinosaurs/xml/dinosaurs.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="dinolist">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="dinosaur" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:string" name="group"/>
              <xs:element name="range">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="region" maxOccurs="unbounded" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="physio">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="length">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:byte">
                            <xs:attribute type="xs:string" name="unit" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="weight">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:float">
                            <xs:attribute type="xs:string" name="unit" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="diet"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="period" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== annush-hub/annush-hub.github.io/dinosaurs/xml/dinosaurs.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="https://annush-hub.github.io/dinosaurs/xml/dinosaurs.xslt"?>
<dinolist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xsi:schemaLocation="http://www.w3.org/2001/XMLSchema-instance
   dinosaurs.xsd">
   <dinosaur period="Late Cretaceous">
      <name>Tyrannosaurus</name>
      <group>Carnosaur</group>
      <range>
         <region>Europe</region>
         <region>North America</region>       
      </range>
      <physio>
         <length unit = "feet">36</length>
         <weight unit = "tons">6</weight>
         <diet>carnivorous </diet>       
      </physio>
   </dinosaur>
   <dinosaur period="Late Jurassic">
      <name>Stegosaurus</name>
      <group>Stegosaur</group>
      <range>
         <region>Europe</region>
         <region>Asia</region>
         <region>North America</region>       
      </range>
      <physio>
         <length unit = "metres">9</length>
         <weight unit = "kgs">3100</weight>
         <diet>herbivorous</diet>        
      </physio>
   </dinosaur>
    <dinosaur period="Late Triassic">
      <name>Coelophysis</name>
      <group>Theropod</group>
      <range>
         <region>Africa</region>
         <region>North America</region>       
      </range>
      <physio>
         <length unit = "feet">6</length>
         <weight unit = "kgs">27</weight>
         <diet>carnivorous </diet>       
      </physio>
   </dinosaur>
   <dinosaur period="Late Jurassic">
      <name>Diplodocus</name>
      <group>Sauropod</group>
      <range>
         <region>North America</region>       
      </range>
      <physio>
         <length unit = "metres">26</length>
         <weight unit = "tons">20</weight>
         <diet>herbivorous</diet>        
      </physio>
   </dinosaur>
   <dinosaur period="Late Cretaceous">
      <name>Triceratops</name>
      <group>Ceratopsian</group>
      <range>
         <region>North America</region>       
      </range>
      <physio>
         <length unit = "metres">9</length>
         <weight unit = "tons">5.5</weight>
         <diet>herbivorous</diet>        
      </physio>
   </dinosaur>
</dinolist>
